/**
 * Henry Stickmin — Constantes de configuración y árbol de escenas (versión extendida)
 */
export const TYPE_SPEED = 30; // ms por carácter

export const SCENES = {
  // ─── ACTO I: EL PLAN ──────────────────────────────────────────────
  intro: {
    id: 'intro',
    title: 'Bienvenido, Henry',
    text: 'Henry Stickmin ha estado planeando el golpe perfecto durante meses.\nHoy es la noche. El museo municipal alberga "El Zafiro Eterno",\nuna joya legendaria. La seguridad es extrema, pero Henry tiene\nmuchas ideas... quizás demasiadas.',
    emoji: '🏛️',
    stickmanPose: 'thinking',
    choices: [
      { label: '🔍 Entrar sigilosamente', next: 'sneak' },
      { label: '💥 Entrar por la fuerza', next: 'force' },
      { label: '🎭 Disfrazarse', next: 'disguise' },
      { label: '💰 Sobornar a un guardia', next: 'bribe' },
      { label: '🛸 Usar tecnología (dron)', next: 'tech' },
    ],
  },

  // ─── ACTO II: INFILTRACIÓN ────────────────────────────────────────

  // === Camino Sigilo ===
  sneak: {
    id: 'sneak',
    title: 'Sigilo profesional',
    text: 'Henry se desliza por los tejados hasta una claraboya.\nAbajo, el museo está oscuro, pero se oyen pasos de guardias.\nTres vías parecen viables.',
    emoji: '🌙',
    stickmanPose: 'crawling',
    choices: [
      { label: '⬇️ Bajar por el conducto de ventilación', next: 'sneak_duct' },
      { label: '🧗 Cruzar por las vigas del techo', next: 'sneak_roof' },
      { label: '🌑 Moverse entre las sombras', next: 'sneak_shadows' },
    ],
  },
  sneak_duct: {
    id: 'sneak_duct',
    title: 'Dentro del conducto',
    text: 'El conducto es estrecho y polvoriento. Henry avanza a gatas.\nLlega a una bifurcación: un ramal va hacia la sala de calderas,\notro hacia los vestuarios.',
    emoji: '🌬️',
    stickmanPose: 'crawling',
    choices: [
      { label: '⬅️ Izquierda: sala de calderas', next: 'sneak_boiler' },
      { label: '➡️ Derecha: vestuarios', next: 'sneak_locker' },
    ],
  },
  sneak_boiler: {
    id: 'sneak_boiler',
    title: 'Sala de calderas',
    text: 'Henry sale del conducto y ve un cartel: "PELIGRO: GAS".\nEn una mesa hay una llave marcada "SALA EXPOSICIONES" y\ntambién un extintor. Los guardias pasan cerca.',
    emoji: '🔥',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🔑 Coger la llave', next: 'vault_key' },
      { label: '🧯 Coger el extintor', next: 'vault_extinguisher' },
      { label: '💨 Encender un fósforo (mala idea)', next: 'fail_explosion' },
    ],
  },
  sneak_locker: {
    id: 'sneak_locker',
    title: 'Vestuarios',
    text: 'Henry encuentra un uniforme de guardia colgado.\nTambién ve una tableta con el mapa del museo y los códigos\nde acceso. Pero un guardia está duchándose.',
    emoji: '🚿',
    stickmanPose: 'hiding',
    choices: [
      { label: '👕 Robar el uniforme y la tableta', next: 'vault_uniform' },
      { label: '🚪 Salir sin hacer ruido', next: 'sneak_roof' }, // vuelve a opción de techo
    ],
  },
  sneak_roof: {
    id: 'sneak_roof',
    title: 'Por las vigas',
    text: 'Henry camina por las vigas de hierro del techo.\nVe la cámara acorazada abajo, pero hay sensores de movimiento\nen el suelo. También hay una cuerda que baja hasta una plataforma.',
    emoji: '🕸️',
    stickmanPose: 'reaching',
    choices: [
      { label: '🧗 Descolgarse por la cuerda', next: 'vault_rope' },
      { label: '🔄 Buscar otro camino', next: 'sneak_shadows' },
    ],
  },
  sneak_shadows: {
    id: 'sneak_shadows',
    title: 'Entre sombras',
    text: 'Henry se pega a las paredes, moviéndose de columna en columna.\nLlega a la entrada de la cámara acorazada. Hay dos guardias\ncharlando y una puerta con cerradura electrónica.',
    emoji: '🌑',
    stickmanPose: 'hiding',
    choices: [
      { label: '👀 Escuchar la conversación (obtener código)', next: 'vault_code' },
      { label: '💤 Dormir a los guardias con gas somnífero', next: 'vault_gas' },
    ],
  },

  // === Camino Fuerza ===
  force: {
    id: 'force',
    title: 'A lo bestia',
    text: 'Henry saca su mochila de herramientas. Tiene un martillo\nneumático, explosivos y un ariete. ¿Qué usa para abrirse paso?',
    emoji: '🔨',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🧱 Martillo neumático (pared)', next: 'force_hammer' },
      { label: '💥 Explosivos (puerta blindada)', next: 'force_explosives' },
      { label: '🚪 Ariete (puerta principal)', next: 'force_ram' },
    ],
  },
  force_hammer: {
    id: 'force_hammer',
    title: 'Taladrando la pared',
    text: 'Henry rompe la pared trasera de la cámara acorazada.\nEl ruido atrae a los guardias, pero Henry ya está dentro.\nEl zafiro está en un pedestal con un sensor de presión.',
    emoji: '🧱',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🏃 Coger el zafiro y huir', next: 'force_escape_hammer' },
      { label: '🪤 Esconderse y esperar', next: 'fail_curtain' }, // similar al original pero con más contexto
    ],
  },
  force_explosives: {
    id: 'force_explosives',
    title: '¡KABOOM!',
    text: 'Henry coloca los explosivos en la puerta blindada.\nLa explosión es enorme... demasiado. Derriba media pared,\npero también activa la alarma general. Henry entra a la carrera.',
    emoji: '💥',
    stickmanPose: 'running',
    choices: [
      { label: '💨 Coger el zafiro y salir', next: 'force_escape_boom' },
      { label: '🆘 Buscar una salida alternativa', next: 'fail_alarm' },
    ],
  },
  force_ram: {
    id: 'force_ram',
    title: 'Ariete contra la puerta',
    text: 'Henry embiste la puerta principal con el ariete.\nLa puerta cede, pero el ruido es ensordecedor. Dentro,\nun guardia sorprendido le apunta con una pistola.',
    emoji: '🚪',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🤜 Desarmar al guardia', next: 'vault_ram_guard' },
      { label: '🏃 Esquivar y correr', next: 'vault_ram_run' },
    ],
  },

  // === Camino Disfraz ===
  disguise: {
    id: 'disguise',
    title: 'Disfraz y actuación',
    text: 'Henry tiene varios uniformes en su mochila: de guardia,\nde limpiador y de científico. También una máscara de la\ndirectora del museo. ¿Cuál elige?',
    emoji: '🎭',
    stickmanPose: 'nervous',
    choices: [
      { label: '👮 Uniforme de guardia', next: 'disguise_guard' },
      { label: '🧹 Uniforme de limpiador', next: 'disguise_janitor' },
      { label: '🔬 Uniforme de científico', next: 'disguise_scientist' },
      { label: '👩 Máscara de la directora', next: 'disguise_director' },
    ],
  },
  disguise_guard: {
    id: 'disguise_guard',
    title: 'Falso guardia',
    text: 'Henry se pone el uniforme, pero la placa dice "Bruce".\nSe encuentra con el guardia Nelson, que le pregunta\npor qué no está en su puesto.',
    emoji: '👮',
    stickmanPose: 'sweating',
    choices: [
      { label: '🗣️ Inventar una historia convincente', next: 'vault_bluff' },
      { label: '😅 Actuar con torpeza (nervioso)', next: 'disguise_clumsy' },
      { label: '🏃 Salir corriendo', next: 'fail_chase' },
    ],
  },
  disguise_janitor: {
    id: 'disguise_janitor',
    title: 'Limpiador de incógnito',
    text: 'Henry empuja un carrito de limpieza. Nadie le presta atención.\nLlega a la cámara acorazada, pero hay un código de acceso\nen la puerta. El carrito tiene una caja de herramientas.',
    emoji: '🧹',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🔧 Forzar la cerradura con las herramientas', next: 'vault_janitor_tools' },
      { label: '👀 Observar a un empleado que introduce el código', next: 'vault_janitor_code' },
    ],
  },
  disguise_scientist: {
    id: 'disguise_scientist',
    title: 'Científico loco',
    text: 'Henry se pone una bata y gafas. Parece un investigador.\nEntra en el laboratorio del museo, donde hay un ordenador\ncon los planos de seguridad. También hay un robot de limpieza.',
    emoji: '🔬',
    stickmanPose: 'thinking',
    choices: [
      { label: '💻 Descargar los planos', next: 'success_plans' },
      { label: '🤖 Hackear el robot para que cause una distracción', next: 'vault_robot' },
    ],
  },
  disguise_director: {
    id: 'disguise_director',
    title: 'La directora',
    text: 'Henry se pone la máscara y el traje de la directora.\nLos guardias le saludan con respeto. Puede ordenar\nque le abran la cámara acorazada sin problemas.',
    emoji: '👩‍💼',
    stickmanPose: 'walking_away',
    choices: [
      { label: '👑 Ordenar que abran la cámara', next: 'vault_director_open' },
      { label: '📋 Pedir el informe de seguridad (para obtener códigos)', next: 'vault_director_codes' },
    ],
  },

  // === Camino Soborno ===
  bribe: {
    id: 'bribe',
    title: 'El soborno',
    text: 'Henry localiza a un guardia llamado Mike, conocido por ser corrupto.\nLe ofrece un fajo de billetes a cambio de acceso a la cámara.\nMike duda...',
    emoji: '💰',
    stickmanPose: 'nervous',
    choices: [
      { label: '💰 Aumentar la oferta', next: 'bribe_accept' },
      { label: '😡 Amenazar con denunciarlo', next: 'bribe_threat' },
      { label: '🤝 Ofrecerle un porcentaje del botín', next: 'bribe_partner' },
    ],
  },
  bribe_accept: {
    id: 'bribe_accept',
    title: 'Trato hecho',
    text: 'Mike acepta el dinero y abre la puerta trasera.\nHenry entra en la cámara sin problemas. Pero Mike activa\nuna alarma silenciosa para quedarse con todo.',
    emoji: '🤝',
    stickmanPose: 'walking_away',
    choices: [
      { label: '🏃 Coger el zafiro y huir antes de que lleguen', next: 'vault_bribe_escape' },
      { label: '🔫 Enfrentarse a Mike', next: 'fail_bribe_fight' },
    ],
  },
  bribe_threat: {
    id: 'bribe_threat',
    title: 'Amenaza',
    text: 'Mike se asusta y llama a sus compañeros. Henry tiene que\nhuir por los pasillos del museo mientras suena la alarma.',
    emoji: '😱',
    stickmanPose: 'running',
    choices: [
      { label: '🏃 Correr hacia la salida', next: 'fail_chase' },
      { label: '🕵️ Esconderse en el armario', next: 'fail_hide' },
    ],
  },
  bribe_partner: {
    id: 'bribe_partner',
    title: 'Socio en el crimen',
    text: 'Mike acepta unirse a Henry. Juntos planean el golpe.\nMike sabe todos los códigos y las rutas de seguridad.\nEl plan es perfecto... pero Mike es un poco torpe.',
    emoji: '🤝',
    stickmanPose: 'pointing',
    choices: [
      { label: '🔑 Dejar que Mike abra la cámara', next: 'vault_partner_open' },
      { label: '📱 Seguir el plan de Henry (más seguro)', next: 'vault_partner_plan' },
    ],
  },

  // === Camino Tecnología ===
  tech: {
    id: 'tech',
    title: 'Alta tecnología',
    text: 'Henry despliega un dron con cámara y herramientas.\nPuede usarlo para desactivar alarmas, abrir cerraduras\ny distraer guardias. Pero el dron tiene poca batería.',
    emoji: '🛸',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🚁 Desactivar la alarma principal con el dron', next: 'tech_disable' },
      { label: '🔓 Abrir la cerradura de la cámara con el dron', next: 'tech_open' },
      { label: '📸 Usar el dron para grabar los códigos', next: 'tech_record' },
    ],
  },
  tech_disable: {
    id: 'tech_disable',
    title: 'Alarma desactivada',
    text: 'El dron se cuela en la sala de control y desconecta la alarma.\nHenry puede entrar sin ser detectado. Pero el dron se queda sin batería.',
    emoji: '🚁',
    stickmanPose: 'reaching',
    choices: [
      { label: '🔑 Entrar directamente a la cámara', next: 'vault_tech_direct' },
      { label: '🔍 Buscar una ruta alternativa (por si acaso)', next: 'sneak_roof' }, // vuelve a opción de techo
    ],
  },
  tech_open: {
    id: 'tech_open',
    title: 'Apertura remota',
    text: 'El dron abre la cerradura de la cámara acorazada.\nHenry entra sin problemas. El zafiro está frente a él,\npero hay un sensor de peso en el suelo.',
    emoji: '🔓',
    stickmanPose: 'reaching',
    choices: [
      { label: '🕺 Bailar para evitar el sensor', next: 'success_dance' },
      { label: '🏋️ Saltar el sensor', next: 'fail_sensor' },
    ],
  },
  tech_record: {
    id: 'tech_record',
    title: 'Grabación de códigos',
    text: 'El dron graba a un guardia introduciendo el código de la cámara.\nHenry lo anota. Pero el guardia nota el dron y da la alarma.',
    emoji: '📸',
    stickmanPose: 'thinking',
    choices: [
      { label: '🏃 Usar el código antes de que cambien', next: 'vault_code_fast' },
      { label: '🕵️ Esperar a que se calme la situación', next: 'fail_alarm' },
    ],
  },

  // ─── ACTO III: EL ZAFIRO (escenas de acceso y resolución) ──────

  // Escenas comunes de acceso (algunas ya definidas arriba, pero completamos)
  vault_key: {
    id: 'vault_key',
    title: 'Llave en mano',
    text: 'Henry usa la llave para abrir la puerta trasera de la cámara.\nEl zafiro brilla en el interior. Hay un sensor de peso en el suelo.',
    emoji: '💎',
    stickmanPose: 'reaching',
    choices: [
      { label: '🕺 Bailar para engañar al sensor', next: 'success_dance' },
      { label: '⚖️ Buscar un objeto pesado para poner en el sensor', next: 'vault_weight' },
    ],
  },
  vault_extinguisher: {
    id: 'vault_extinguisher',
    title: 'Extintor sorpresa',
    text: 'Henry entra con el extintor. El zafiro está tras un cristal blindado.\nPuede romper el cristal con el extintor, pero hará ruido.',
    emoji: '🧯',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🔊 Romper el cristal y salir rápido', next: 'success_coffee' }, // reutilizamos éxito café
      { label: '🔍 Buscar un botón de apertura', next: 'fail_buttons' },
    ],
  },
  vault_uniform: {
    id: 'vault_uniform',
    title: 'Uniforme y tableta',
    text: 'Henry se pone el uniforme y usa la tableta para desactivar los sensores.\nEntra en la cámara como si fuera un guardia más. El zafiro está al alcance.',
    emoji: '👔',
    stickmanPose: 'walking_away',
    choices: [
      { label: '✅ Tomar el zafiro y salir con naturalidad', next: 'success_bluff' },
      { label: '📞 Llamar por radio al jefe (error)', next: 'fail_radio' },
    ],
  },
  vault_rope: {
    id: 'vault_rope',
    title: 'Desde arriba',
    text: 'Henry se descuelga por la cuerda y aterriza justo al lado del zafiro.\nNo hay sensores en esa zona. Toma la joya y sube de nuevo.',
    emoji: '🧗',
    stickmanPose: 'reaching',
    choices: [
      { label: '🏃 Escalar rápido', next: 'success_rope' },
      { label: '📸 Tomarse un selfie con el zafiro (pérdida de tiempo)', next: 'fail_selfie' },
    ],
  },
  vault_code: {
    id: 'vault_code',
    title: 'Código obtenido',
    text: 'Henry escucha a los guardias: el código es 8675309.\nIntroduce el código y la puerta se abre. El zafiro está dentro,\npero hay un sistema de riego antincendios que puede activarse.',
    emoji: '🔢',
    stickmanPose: 'thinking',
    choices: [
      { label: '💨 Entrar rápido y coger el zafiro', next: 'success_code' },
      { label: '🚿 Probar a ver si el sistema de riego funciona', next: 'fail_sprinkler' },
    ],
  },
  vault_gas: {
    id: 'vault_gas',
    title: 'Gas somnífero',
    text: 'Henry usa el gas para dormir a los guardias. Luego abre la puerta\ny entra sin problemas. Pero el gas también afecta a Henry,\nque empieza a sentirse somnoliento.',
    emoji: '💤',
    stickmanPose: 'ko',
    choices: [
      { label: '💪 Coger el zafiro y salir antes de dormirse', next: 'success_gas' },
      { label: '😴 Dejarse llevar por el sueño', next: 'fail_gas_sleep' },
    ],
  },
  vault_ram_guard: {
    id: 'vault_ram_guard',
    title: 'Desarme',
    text: 'Henry desarma al guardia con una llave de karate. El guardia cae.\nHenry tiene el control de la cámara. El zafiro está en una vitrina.',
    emoji: '🥋',
    stickmanPose: 'fighting',
    choices: [
      { label: '🔨 Romper la vitrina y huir', next: 'success_ram' },
      { label: '🔑 Buscar la llave de la vitrina', next: 'vault_ram_key' },
    ],
  },
  vault_ram_run: {
    id: 'vault_ram_run',
    title: 'Esquivar y correr',
    text: 'Henry esquiva al guardia y corre hacia la vitrina. Pero el guardia\ndispara un dardo tranquilizante que roza a Henry.',
    emoji: '🏃',
    stickmanPose: 'running',
    choices: [
      { label: '💨 Ignorar el dardo y coger el zafiro', next: 'success_ram_run' },
      { label: '🛑 Pararse a quitarlo (pérdida de tiempo)', next: 'fail_tranquilizer' },
    ],
  },
  vault_bluff: {
    id: 'vault_bluff',
    title: 'El farol de Bruce',
    text: 'Henry convence al guardía Nelson de que está haciendo un inventario.\nNelson le deja pasar. Dentro, el zafiro está en un pedestal.\nPero Henry nota que Nelson lo mira con suspicacia.',
    emoji: '😅',
    stickmanPose: 'sweating',
    choices: [
      { label: '✅ Coger el zafiro y salir con naturalidad', next: 'success_bluff' },
      { label: '📞 Llamar por radio para confirmar', next: 'fail_radio' },
    ],
  },
  vault_janitor_tools: {
    id: 'vault_janitor_tools',
    title: 'Herramientas de limpieza',
    text: 'Henry usa las herramientas del carrito para forzar la cerradura.\nEntra y ve el zafiro, pero también un cartel que dice: "No tocar".',
    emoji: '🔧',
    stickmanPose: 'holding_tool',
    choices: [
      { label: '🔧 Ignorar el cartel y tomar el zafiro', next: 'success_janitor' },
      { label: '📖 Leer el cartel (es una trampa)', next: 'fail_janitor_trap' },
    ],
  },
  vault_janitor_code: {
    id: 'vault_janitor_code',
    title: 'Código visto',
    text: 'Henry ve a un empleado teclear el código: 1234.\nEntra, pero el empleado lo descubre y se pone a gritar.',
    emoji: '👀',
    stickmanPose: 'hiding',
    choices: [
      { label: '💨 Coger el zafiro y huir', next: 'success_janitor_code' },
      { label: '😇 Intentar explicar que es un error', next: 'fail_explain' },
    ],
  },
  vault_robot: {
    id: 'vault_robot',
    title: 'Robot de distracción',
    text: 'Henry hackea el robot de limpieza y lo programa para que cause\nun pequeño incendio. Los guardias corren hacia el humo.\nHenry entra en la cámara sin oposición.',
    emoji: '🤖',
    stickmanPose: 'pointing',
    choices: [
      { label: '🔥 Coger el zafiro y salir', next: 'success_robot' },
      { label: '🎥 Grabar el caos para el recuerdo', next: 'fail_robot_selfie' },
    ],
  },
  vault_director_open: {
    id: 'vault_director_open',
    title: 'Orden ejecutiva',
    text: 'Henry, con la máscara de la directora, ordena que abran la cámara.\nLos guardias obedecen. El zafiro está expuesto. Pero la directora real\naparece por detrás.',
    emoji: '👩‍💼',
    stickmanPose: 'nervous',
    choices: [
      { label: '🏃 Coger el zafiro y huir', next: 'success_director_escape' },
      { label: '😅 Intentar engañar a la directora', next: 'fail_director' },
    ],
  },
  vault_director_codes: {
    id: 'vault_director_codes',
    title: 'Códigos de la directora',
    text: 'Henry pide los códigos de seguridad. La directora real se los da,\npero nota que algo raro. Henry se va rápidamente y usa los códigos\npara abrir la cámara.',
    emoji: '📋',
    stickmanPose: 'walking_away',
    choices: [
      { label: '🔓 Abrir la cámara y tomar el zafiro', next: 'success_director_codes' },
      { label: '🕵️ Dejar una nota de agradecimiento', next: 'fail_note' },
    ],
  },
  vault_bribe_escape: {
    id: 'vault_bribe_escape',
    title: 'Huida del soborno',
    text: 'Henry toma el zafiro y sale corriendo. Mike activó la alarma,\npero Henry logra escapar por una ventana. La policía llega tarde.',
    emoji: '💨',
    stickmanPose: 'running',
    choices: [
      { label: '🏃 Saltar al coche de la fuga', next: 'success_bribe_escape' },
      { label: '🛵 Tomar una moto de policía', next: 'success_bribe_moto' },
    ],
  },
  vault_partner_open: {
    id: 'vault_partner_open',
    title: 'Socio abre la cámara',
    text: 'Mike usa sus códigos para abrir la cámara. El zafiro es suyo,\npero Mike se vuelve codicioso y quiere quedarse con todo.',
    emoji: '🤝',
    stickmanPose: 'pointing',
    choices: [
      { label: '⚔️ Enfrentarse a Mike por el botín', next: 'fail_partner_betrayal' },
      { label: '🤝 Negociar un reparto justo', next: 'success_partner' },
    ],
  },
  vault_partner_plan: {
    id: 'vault_partner_plan',
    title: 'Plan de Henry',
    text: 'Henry sigue su propio plan, dejando a Mike como distracción.\nHenry entra en la cámara, toma el zafiro y sale sin ser visto.\nMike es arrestado, pero Henry escapa.',
    emoji: '🗺️',
    stickmanPose: 'walking_away',
    choices: [
      { label: '🏃 Escapar por la azotea', next: 'success_partner_plan' },
      { label: '🚗 Escapar en el coche de Mike', next: 'success_partner_car' },
    ],
  },
  vault_tech_direct: {
    id: 'vault_tech_direct',
    title: 'Acceso directo con tecnología',
    text: 'Henry entra directamente a la cámara. El zafiro está en una caja fuerte\ngiratoria. Henry usa el dron para girar la rueda y abrirla.',
    emoji: '💎',
    stickmanPose: 'reaching',
    choices: [
      { label: '💪 Abrir la caja fuerte y tomar el zafiro', next: 'success_tech_direct' },
      { label: '🔢 Intentar adivinar la combinación', next: 'fail_tech_guess' },
    ],
  },
  vault_code_fast: {
    id: 'vault_code_fast',
    title: 'Código rápido',
    text: 'Henry usa el código grabado para abrir la cámara, pero la alarma\nsigue sonando. Tiene que ser rápido. El zafiro está en una vitrina\ncon un mecanismo de cierre automático.',
    emoji: '⏱️',
    stickmanPose: 'running',
    choices: [
      { label: '🔨 Romper la vitrina y huir', next: 'success_code_fast' },
      { label: '🔑 Buscar la llave de la vitrina', next: 'fail_code_slow' },
    ],
  },
  vault_weight: {
    id: 'vault_weight',
    title: 'Peso muerto',
    text: 'Henry pone un extintor sobre el sensor de peso. El sistema cree\nque hay alguien de pie y desactiva la alarma. Henry toma el zafiro.',
    emoji: '⚖️',
    stickmanPose: 'reaching',
    choices: [
      { label: '🏃 Salir con el zafiro', next: 'success_weight' },
      { label: '🎭 Hacer una pose triunfal (pérdida de tiempo)', next: 'fail_weight_pose' },
    ],
  },
  vault_ram_key: {
    id: 'vault_ram_key',
    title: 'La llave de la vitrina',
    text: 'Henry encuentra la llave de la vitrina en el cinturón del guardia\ndesarmado. La abre y toma el zafiro. El guardia se despierta.',
    emoji: '🔑',
    stickmanPose: 'reaching',
    choices: [
      { label: '💨 Huir antes de que se recupere', next: 'success_ram_key' },
      { label: '😈 Devolverle la llave con una burla', next: 'fail_ram_taunt' },
    ],
  },

  // ─── ACTO IV: LA HUIDA (finales) ──────────────────────────────────

  // Aquí van los finales, muchos ya definidos como 'ending' en las escenas anteriores,
  // pero también podemos tener escenas de huida que lleven a finales específicos.

  // ─── BUCLES Y REUTILIZACIÓN DE PERSONAJES ──────────────────────────
  // Mike el guardia corrupto aparece en más caminos
  disguise_clumsy: {
    id: 'disguise_clumsy',
    title: 'Torpeza legendaria',
    text: 'Henry tartamudea y casi se cae. El guardia Nelson se ríe y le\ndice que vaya a la sala de descanso. Allí se encuentra con Mike,\nel guardia corrupto del plan de soborno.',
    emoji: '😅',
    stickmanPose: 'facepalm',
    choices: [
      { label: '💰 Intentar sobornar a Mike', next: 'bribe_accept' },
      { label: '😰 Huir de la sala', next: 'fail_chase' },
      { label: '👔 Cambiarse al uniforme de limpiador', next: 'disguise_janitor' },
    ],
  },
  force_escape_hammer: {
    id: 'force_escape_hammer',
    title: 'Huida con martillo',
    text: 'Henry coge el zafiro y corre hacia la salida. Los guardias lo\nsiguen, pero Henry abre un boquete en otra pared y sale a la calle.',
    emoji: '🏃',
    stickmanPose: 'running',
    choices: [
      { label: '🏃 Correr hacia el coche', next: 'success_ram' },
      { label: '🚇 Meterte en el metro', next: 'fail_chase' },
    ],
  },
  force_escape_boom: {
    id: 'force_escape_boom',
    title: 'Huida explosiva',
    text: 'Henry sale corriendo con el zafiro mientras la alarma suena.\nLos guardias están confundidos por la explosión. Ve a Mike\nentre ellos, que lo reconoce.',
    emoji: '💨',
    stickmanPose: 'running',
    choices: [
      { label: '💰 Ofrecer a Mike una parte', next: 'bribe_partner' },
      { label: '💨 Ignorarlo y seguir corriendo', next: 'success_bribe_escape' },
    ],
  },

  // Más probabilidad de fracaso: reutilizar escenas de fracaso en más caminos
  sneak_shadows: {  // ampliar opciones
    id: 'sneak_shadows',
    title: 'Entre sombras',
    text: 'Henry se pega a las paredes, moviéndose de columna en columna.\nLlega a la entrada de la cámara acorazada. Hay dos guardias\ncharlando y una puerta con cerradura electrónica.',
    emoji: '🌑',
    stickmanPose: 'hiding',
    choices: [
      { label: '👀 Escuchar la conversación (obtener código)', next: 'vault_code' },
      { label: '💤 Dormir a los guardias con gas somnífero', next: 'vault_gas' },
      { label: '😰 Estornudar y delatarte', next: 'fail_chase' },
    ],
  },
  vault_code_fast: {  // ampliar opciones
    id: 'vault_code_fast',
    title: 'Código rápido',
    text: 'Henry usa el código grabado para abrir la cámara, pero la alarma\nsigue sonando. Tiene que ser rápido. El zafiro está en una vitrina\ncon un mecanismo de cierre automático.',
    emoji: '⏱️',
    stickmanPose: 'running',
    choices: [
      { label: '🔨 Romper la vitrina y huir', next: 'success_code_fast' },
      { label: '🔑 Buscar la llave de la vitrina', next: 'fail_code_slow' },
      { label: '🤝 Pedir ayuda a Mike (que aparece por casualidad)', next: 'bribe_partner' },
    ],
  },

  // ─── FINALES DE ÉXITO ─────────────────────────────────────────────
  success_dance: {
    id: 'success_dance',
    title: '🎉 ¡Bailando hacia la libertad!',
    text: 'Henry pone música y baila sobre el sensor de peso.\nEl sistema no detecta peso constante, así que la alarma no salta.\nToma el zafiro y sale bailando del museo.',
    emoji: '💃',
    stickmanPose: 'dancing',
    ending: { type: 'success', text: '¡Zafiro conseguido! Henry se convierte en una leyenda del baile y del crimen.' },
  },
  success_coffee: {
    id: 'success_coffee',
    title: '☕ ¡Café y zafiro!',
    text: 'Henry rompe el cristal con el extintor, toma el zafiro y sale.\nEl guardia dormido sigue soñando con un café perfecto.',
    emoji: '☕',
    stickmanPose: 'running',
    ending: { type: 'success', text: 'Misión cumplida. El Zafiro Eterno ahora brilla en la guarida de Henry.' },
  },
  success_bluff: {
    id: 'success_bluff',
    title: '🎭 El mejor farol',
    text: 'Henry sale caminando tranquilamente, con el zafiro en el bolsillo,\nsaluda a Nelson y desaparece en la noche.',
    emoji: '🎭',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'Nadie supo que "Bruce" era Henry Stickmin. El crimen perfecto.' },
  },
  success_plans: {
    id: 'success_plans',
    title: '📸 Plan maestro',
    text: 'Henry fotografía los planos y conoce todos los secretos del museo.\nEjecuta el robo sin un solo error. El zafiro es suyo.',
    emoji: '📸',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'El golpe más limpio de la historia. Henry se retira... por ahora.' },
  },
  success_rope: {
    id: 'success_rope',
    title: '🧗 Escalada exitosa',
    text: 'Henry sube por la cuerda con el zafiro y escapa por el techo.\nLos guardias solo ven una sombra.',
    emoji: '🧗',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'Henry demuestra que a veces la altura es la mejor aliada.' },
  },
  success_code: {
    id: 'success_code',
    title: '🔢 Código perfecto',
    text: 'Henry introduce el código y la puerta se abre. Toma el zafiro y\nsale antes de que el sistema de riego se active.',
    emoji: '🔢',
    stickmanPose: 'running',
    ending: { type: 'success', text: 'Números y suerte: la combinación ganadora.' },
  },
  success_gas: {
    id: 'success_gas',
    title: '💤 Gas y victoria',
    text: 'Henry aguanta la respiración lo suficiente para coger el zafiro\ny salir antes de caer dormido. Despierta horas después con la joya.',
    emoji: '💤',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'Un robo con siesta incluida. Henry lo ha vuelto a hacer.' },
  },
  success_ram: {
    id: 'success_ram',
    title: '🔨 Martillo de campeón',
    text: 'Henry rompe la vitrina con el martillo, toma el zafiro y sale\npor el agujero de la pared antes de que lleguen los refuerzos.',
    emoji: '🔨',
    stickmanPose: 'running',
    ending: { type: 'success', text: 'La fuerza bruta a veces es la solución más elegante.' },
  },
  success_ram_run: {
    id: 'success_ram_run',
    title: '🏃 Carrera contrarreloj',
    text: 'Henry esquiva el dardo, coge el zafiro y corre hasta el coche de\nla fuga. Los guardias no pueden alcanzarlo.',
    emoji: '🏃',
    stickmanPose: 'running',
    ending: { type: 'success', text: 'Velocidad y reflejos: Henry es imparable.' },
  },
  success_janitor: {
    id: 'success_janitor',
    title: '🧹 Limpiador de lujo',
    text: 'Henry ignora el cartel y toma el zafiro. Sale empujando el carrito\ncomo si nada. Nadie sospecha del limpiador.',
    emoji: '🧹',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'El mejor disfraz es el más común. Henry lo sabía.' },
  },
  success_janitor_code: {
    id: 'success_janitor_code',
    title: '👀 Código y huida',
    text: 'Henry corre con el zafiro mientras el empleado grita. Logra\nesconderse en un armario hasta que pasa el peligro.',
    emoji: '👀',
    stickmanPose: 'hiding',
    ending: { type: 'success', text: 'Un buen escondite puede salvar un robo.' },
  },
  success_robot: {
    id: 'success_robot',
    title: '🤖 Robot aliado',
    text: 'Henry toma el zafiro mientras el robot provoca un incendio falso.\nSale sin problemas, dejando a los guardias confundidos.',
    emoji: '🤖',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'La tecnología al servicio del crimen.' },
  },
  success_director_escape: {
    id: 'success_director_escape',
    title: '👩‍💼 Huyendo de la directora',
    text: 'Henry coge el zafiro y corre, la directora real grita, pero él\nya está lejos. Su máscara le permitió llegar hasta el final.',
    emoji: '👩‍💼',
    stickmanPose: 'running',
    ending: { type: 'success', text: 'Impersonar a la jefa tiene sus ventajas.' },
  },
  success_director_codes: {
    id: 'success_director_codes',
    title: '📋 Códigos y victoria',
    text: 'Henry usa los códigos para abrir la cámara, toma el zafiro y\ndeja una nota de agradecimiento. La directora no sabe qué pasó.',
    emoji: '📋',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'Cortesía y eficiencia: el sello de Henry Stickmin.' },
  },
  success_bribe_escape: {
    id: 'success_bribe_escape',
    title: '💨 Fuga sobornada',
    text: 'Henry salta al coche de la fuga y escapa. Mike se queda con las\nganas y con la alarma en la mano.',
    emoji: '💨',
    stickmanPose: 'driving',
    ending: { type: 'success', text: 'El soborno funciona... si sabes cuándo huir.' },
  },
  success_bribe_moto: {
    id: 'success_bribe_moto',
    title: '🏍️ Moto policial',
    text: 'Henry roba una moto de la policía y se pierde entre el tráfico.\nEl zafiro está a salvo y Henry se siente como en una película.',
    emoji: '🏍️',
    stickmanPose: 'driving',
    ending: { type: 'success', text: 'Huir a lo grande: Henry es un artista del escape.' },
  },
  success_partner: {
    id: 'success_partner',
    title: '🤝 Socio de confianza',
    text: 'Henry negocia con Mike y reparten el botín. Ambos se convierten\nen una pareja de ladrones legendarios.',
    emoji: '🤝',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'La amistad (y el dinero) lo puede todo.' },
  },
  success_partner_plan: {
    id: 'success_partner_plan',
    title: '🗺️ Plan de escape',
    text: 'Henry escapa por la azotea mientras Mike es arrestado. El zafiro\nes suyo y Mike nunca lo delató.',
    emoji: '🗺️',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'Un socio útil es aquel que se queda atrás.' },
  },
  success_partner_car: {
    id: 'success_partner_car',
    title: '🚗 Coche de Mike',
    text: 'Henry roba el coche de Mike y se va. Mike, esposado, lo ve alejarse\ncon una sonrisa resignada.',
    emoji: '🚗',
    stickmanPose: 'driving',
    ending: { type: 'success', text: 'Nunca confíes del todo en tu socio.' },
  },
  success_tech_direct: {
    id: 'success_tech_direct',
    title: '🛸 Tecnología imparable',
    text: 'El dron abre la caja fuerte, Henry toma el zafiro y el dron se\nautodestruye para borrar las huellas. Perfecto.',
    emoji: '🛸',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'Crimen de alta tecnología: Henry está a la vanguardia.' },
  },
  success_code_fast: {
    id: 'success_code_fast',
    title: '⏱️ Rápido y furioso',
    text: 'Henry rompe la vitrina, coge el zafiro y sale antes de que el\nsistema de cierre se active. La velocidad es su aliada.',
    emoji: '⏱️',
    stickmanPose: 'running',
    ending: { type: 'success', text: 'Cuando el tiempo es oro, Henry es millonario.' },
  },
  success_weight: {
    id: 'success_weight',
    title: '⚖️ Peso y victoria',
    text: 'Henry usa el extintor para engañar al sensor, toma el zafiro y sale\nsin problemas. La física está de su lado.',
    emoji: '⚖️',
    stickmanPose: 'walking_away',
    ending: { type: 'success', text: 'La ciencia también puede ser una herramienta de robo.' },
  },
  success_ram_key: {
    id: 'success_ram_key',
    title: '🔑 Llave y huida',
    text: 'Henry abre la vitrina, toma el zafiro y corre antes de que el guardia\nse recupere. El golpe es perfecto.',
    emoji: '🔑',
    stickmanPose: 'running',
    ending: { type: 'success', text: 'Una llave puede abrir muchas puertas... y también la fama.' },
  },

  // ─── FINALES DE FRACASO ───────────────────────────────────────────
  fail_explosion: {
    id: 'fail_explosion',
    title: '💥 ¡KABOOM!',
    text: 'Henry enciende un fósforo en la sala de calderas. La explosión\nlo lanza por los aires. Aterriza en la comisaría.',
    emoji: '💥',
    stickmanPose: 'flying',
    ending: { type: 'fail', text: 'Henry es arrestado y se gana el apodo de "El Ruidoso".' },
  },
  fail_curtain: {
    id: 'fail_curtain',
    title: '🎪 Cortina fatal',
    text: 'Henry se esconde detrás de una cortina, pero es una puerta que da\na un cuarto de limpieza lleno de productos químicos. Un bote de\nlejía le cae en la cabeza.',
    emoji: '🧹',
    stickmanPose: 'covered',
    ending: { type: 'fail', text: 'Cuando lo encuentran, huele a lejía y está blanco como una nube.' },
  },
  fail_alarm: {
    id: 'fail_alarm',
    title: '🚨 ¡Alarma general!',
    text: 'La alarma se activa y 50 guardias rodean a Henry en segundos.\nNo hay escapatoria.',
    emoji: '🚨',
    stickmanPose: 'trapped',
    ending: { type: 'fail', text: '"Pensamos que sería más astuto", dijo el jefe de seguridad.' },
  },
  fail_chase: {
    id: 'fail_chase',
    title: '🏃 Persecución fallida',
    text: 'Henry corre pero tropieza con sus propios cordones y cae rodando\npor una escalera. Los guardias lo alcanzan fácilmente.',
    emoji: '🏃',
    stickmanPose: 'tripping',
    ending: { type: 'fail', text: 'Una caída épica que será recordada en los archivos policiales.' },
  },
  fail_sensor: {
    id: 'fail_sensor',
    title: '🔒 Sensor de peso',
    text: 'Henry salta y cae justo sobre el sensor. La alarma se activa,\nel zafiro se retrae al techo y las puertas blindadas sellan la sala.',
    emoji: '🔒',
    stickmanPose: 'trapped',
    ending: { type: 'fail', text: 'Henry queda atrapado y los guardias se ríen de su intento de salto.' },
  },
  fail_buttons: {
    id: 'fail_buttons',
    title: '🎮 Demasiados botones',
    text: 'Henry prueba todos los botones del panel. La puerta se cierra,\nlas luces se apagan y un brazo robótico le quita el zafiro.',
    emoji: '🤖',
    stickmanPose: 'confused',
    ending: { type: 'fail', text: 'El museo contrata al creador del brazo robótico. Henry no tuvo oportunidad.' },
  },
  fail_radio: {
    id: 'fail_radio',
    title: '📻 Radio accidente',
    text: 'Henry usa la radio para pedir instrucciones, pero revela su identidad.\nEl jefe de seguridad lo localiza y lo arresta.',
    emoji: '📻',
    stickmanPose: 'facepalm',
    ending: { type: 'fail', text: 'Arruinado por una conversación de radio. Henry no aprende.' },
  },
  fail_bribe_fight: {
    id: 'fail_bribe_fight',
    title: '🔫 Pelea por el soborno',
    text: 'Henry se enfrenta a Mike, pero Mike resulta ser un exboxeador.\nHenry acaba noqueado y sin zafiro.',
    emoji: '🤛',
    stickmanPose: 'ko',
    ending: { type: 'fail', text: 'Mike se queda con el dinero y el zafiro. Henry aprende a no sobornar a exboxeadores.' },
  },
  fail_hide: {
    id: 'fail_hide',
    title: '🕵️ Escondite patético',
    text: 'Henry se esconde en un armario, pero es el armario de los trapos\nsucios. Los guardias lo encuentran oliendo a humedad.',
    emoji: '🚪',
    stickmanPose: 'hiding',
    ending: { type: 'fail', text: 'El peor escondite de la historia. Henry lo recuerda con vergüenza.' },
  },
  fail_selfie: {
    id: 'fail_selfie',
    title: '📸 Selfie arriesgado',
    text: 'Henry se toma un selfie con el zafiro. El flash alerta a los guardias,\nque lo atrapan con la cámara en la mano.',
    emoji: '📸',
    stickmanPose: 'sweating',
    ending: { type: 'fail', text: 'La vanidad es un pecado capital... y también una condena.' },
  },
  fail_sprinkler: {
    id: 'fail_sprinkler',
    title: '🚿 Riego inesperado',
    text: 'Henry activa el sistema de riego antincendios. El agua lo empapa\ny resbala, golpeándose la cabeza contra el pedestal.',
    emoji: '🚿',
    stickmanPose: 'ko',
    ending: { type: 'fail', text: 'Henry despierta empapado y esposado. El zafiro está a salvo.' },
  },
  fail_gas_sleep: {
    id: 'fail_gas_sleep',
    title: '💤 Siesta eterna',
    text: 'Henry se duerme por el gas. Cuando despierta, está en una celda\ny el zafiro ha desaparecido.',
    emoji: '💤',
    stickmanPose: 'ko',
    ending: { type: 'fail', text: 'El gas somnífero no perdona. Henry soñó con el zafiro... y nada más.' },
  },
  fail_tranquilizer: {
    id: 'fail_tranquilizer',
    title: '💉 Dardo de sueño',
    text: 'Henry se detiene a quitarse el dardo, pero el guardia le dispara\notro. Henry cae dormido en el acto.',
    emoji: '💉',
    stickmanPose: 'ko',
    ending: { type: 'fail', text: 'Los dardos tranquilizantes son más efectivos que el café.' },
  },
  fail_janitor_trap: {
    id: 'fail_janitor_trap',
    title: '📖 Cartel trampa',
    text: 'Henry lee el cartel y, al hacerlo, activa una trampa que lo deja\ncolgado del techo. Los guardias lo encuentran pataleando.',
    emoji: '📖',
    stickmanPose: 'flying',
    ending: { type: 'fail', text: 'Leer puede ser peligroso, sobre todo si es un cartel de "No tocar".' },
  },
  fail_explain: {
    id: 'fail_explain',
    title: '😇 Explicación fallida',
    text: 'Henry intenta convencer al empleado de que es un error, pero el\ntipo no se lo cree y llama a seguridad.',
    emoji: '😇',
    stickmanPose: 'sweating',
    ending: { type: 'fail', text: 'Las explicaciones no sirven cuando tienes un zafiro en la mano.' },
  },
  fail_robot_selfie: {
    id: 'fail_robot_selfie',
    title: '🎥 Selfie en el caos',
    text: 'Henry se detiene a grabar el caos del robot, pero los guardias lo\nven y lo capturan mientras el robot lo graba todo.',
    emoji: '📹',
    stickmanPose: 'sweating',
    ending: { type: 'fail', text: 'El robot se convirtió en testigo estrella del juicio.' },
  },
  fail_director: {
    id: 'fail_director',
    title: '👩‍💼 Enfrentamiento con la directora',
    text: 'Henry intenta engañar a la directora real, pero ella lo descubre\nal instante. Los guardias lo arrestan.',
    emoji: '👩‍💼',
    stickmanPose: 'nervous',
    ending: { type: 'fail', text: 'Impersonar a la directora es un delito grave... y además ella es muy lista.' },
  },
  fail_note: {
    id: 'fail_note',
    title: '📝 Nota de agradecimiento',
    text: 'Henry deja una nota de agradecimiento, pero la directora reconoce\nsu letra y lo rastrea hasta su escondite.',
    emoji: '📝',
    stickmanPose: 'facepalm',
    ending: { type: 'fail', text: 'La cortesía también puede ser un arma de doble filo.' },
  },
  fail_partner_betrayal: {
    id: 'fail_partner_betrayal',
    title: '🗡️ Traición de socio',
    text: 'Henry se enfrenta a Mike, pero Mike tiene un arma oculta.\nHenry termina esposado y Mike se lleva el zafiro.',
    emoji: '🗡️',
    stickmanPose: 'ko',
    ending: { type: 'fail', text: 'Confiar en un socio es el error más común de los ladrones.' },
  },
  fail_tech_guess: {
    id: 'fail_tech_guess',
    title: '🔢 Combinación fallida',
    text: 'Henry intenta adivinar la combinación de la caja fuerte, pero tras\nvarios intentos, el sistema se bloquea y la alarma suena.',
    emoji: '🔢',
    stickmanPose: 'confused',
    ending: { type: 'fail', text: 'El juego de adivinanzas no es lo suyo. La policía lo confirma.' },
  },
  fail_code_slow: {
    id: 'fail_code_slow',
    title: '⏱️ Tiempo agotado',
    text: 'Henry busca la llave de la vitrina, pero el sistema de cierre\nautomático se activa y la vitrina se sella. Henry queda atrapado.',
    emoji: '⏱️',
    stickmanPose: 'trapped',
    ending: { type: 'fail', text: 'El tiempo es oro, pero Henry gastó el suyo buscando llaves.' },
  },
  fail_weight_pose: {
    id: 'fail_weight_pose',
    title: '🎭 Pose triunfal',
    text: 'Henry hace una pose triunfal frente al sensor, pero al mover el\npeso, este cae y activa la alarma. Los guardias lo capturan.',
    emoji: '🎭',
    stickmanPose: 'facepalm',
    ending: { type: 'fail', text: 'El ego es el peor enemigo de un ladrón.' },
  },
  fail_ram_taunt: {
    id: 'fail_ram_taunt',
    title: '😈 Burla costosa',
    text: 'Henry se burla del guardia y le devuelve la llave, pero el guardia\naún consciente lo noquea con un golpe sorpresa.',
    emoji: '😈',
    stickmanPose: 'ko',
    ending: { type: 'fail', text: 'La arrogancia tiene un precio, y Henry lo paga con su libertad.' },
  },
};

export const SCENE_IDS = Object.keys(SCENES);
