/**
 * registry.js
 * Fuente única de verdad de qué juegos existen. Añadir un juego nuevo
 * significa: crear su carpeta en src/games/<id>/, exportar una clase que
 * implemente la Game Interface (ver GameEngine.js), y añadir una entrada
 * aquí. El hub (main.js) no necesita tocarse.
 */
export const GAME_REGISTRY = [
  {
    id: 'breakout',
    title: 'Breakout',
    title_i18n: 'registry.breakout.title',
    tagline: 'Rebotes y destrucción de ladrillos',
    tagline_i18n: 'registry.breakout.tagline',
    level: 1,
    load: () => import('./breakout/index.js').then((m) => m.Breakout),
  },
  {
    id: 'snake',
    title: 'Snake',
    title_i18n: 'registry.snake.title',
    tagline: 'Movimiento en cuadrícula y colisión propia',
    tagline_i18n: 'registry.snake.tagline',
    level: 1,
    load: () => import('./snake/index.js').then((m) => m.Snake),
  },
  {
    id: 'pong',
    title: 'Pong',
    title_i18n: 'registry.pong.title',
    tagline: 'Rebote con ángulo variable vs. IA',
    tagline_i18n: 'registry.pong.tagline',
    level: 1,
    load: () => import('./pong/index.js').then((m) => m.Pong),
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    title_i18n: 'registry.flappy-bird.title',
    tagline: 'Gravedad constante y scroll infinito',
    tagline_i18n: 'registry.flappy-bird.tagline',
    level: 1,
    load: () => import('./flappy-bird/index.js').then((m) => m.FlappyBird),
  },
  {
    id: 'asteroids',
    title: 'Asteroids',
    title_i18n: 'registry.asteroids.title',
    tagline: 'Física de nave: empuje, fricción y wraparound',
    tagline_i18n: 'registry.asteroids.tagline',
    level: 2,
    load: () => import('./asteroids/index.js').then((m) => m.Asteroids),
  },
  {
    id: 'platformer',
    title: 'Platformer',
    title_i18n: 'registry.platformer.title',
    tagline: 'Tilemap, colisión pixel-perfect y cámara con seguimiento',
    tagline_i18n: 'registry.platformer.tagline',
    level: 2,
    load: () => import('./platformer/index.js').then((m) => m.Platformer),
  },
  {
    id: 'fancy-pants',
    title: 'Fancy Pants',
    title_i18n: 'registry.fancy-pants.title',
    tagline: 'Movimiento fluido, hang time y salto en pared',
    tagline_i18n: 'registry.fancy-pants.tagline',
    level: 2,
    load: () => import('./fancy-pants/index.js').then((m) => m.FancyPants),
  },
  {
    id: 'coop-platformer',
    title: 'Fuego y Agua',
    title_i18n: 'registry.coop-platformer.title',
    tagline: 'Cooperativo local: plataforma móvil y palanca',
    tagline_i18n: 'registry.coop-platformer.tagline',
    level: 2,
    load: () => import('./coop-platformer/index.js').then((m) => m.CoopPlatformer),
  },
  {
    id: 'trick-quiz',
    title: 'Trivia Trampa',
    title_i18n: 'registry.trick-quiz.title',
    tagline: 'Máquina de estados: preguntas trampa y zonas ocultas',
    tagline_i18n: 'registry.trick-quiz.tagline',
    level: 3,
    load: () => import('./trick-quiz/index.js').then((m) => m.TrickQuiz),
  },
  {
    id: 'papa-pizzeria',
    title: "Papa's Pizzeria",
    title_i18n: 'registry.papa-pizzeria.title',
    tagline: 'Colas, temporizadores y multitarea culinaria',
    tagline_i18n: 'registry.papa-pizzeria.tagline',
    level: 3,
    load: () => import('./papa-pizzeria/index.js').then((m) => m.PapaPizzeria),
  },
  {
    id: 'stick-rpg',
    title: 'Stick RPG',
    title_i18n: 'registry.stick-rpg.title',
    tagline: 'Días, energía, diálogos y cambio de escenas',
    tagline_i18n: 'registry.stick-rpg.tagline',
    level: 3,
    load: () => import('./stick-rpg/index.js').then((m) => m.StickRPG),
  },
  {
    id: 'crush-the-castle',
    title: 'Crush the Castle',
    title_i18n: 'registry.crush-the-castle.title',
    tagline: 'Proyectiles con física en estructuras',
    tagline_i18n: 'registry.crush-the-castle.tagline',
    level: 4,
    load: () => import('./crush-the-castle/index.js').then((m) => m.CrushTheCastle),
  },
  {
    id: 'bowman',
    title: 'Bowman',
    title_i18n: 'registry.bowman.title',
    tagline: 'Tiro parabólico con viento',
    tagline_i18n: 'registry.bowman.tagline',
    level: 4,
    load: () => import('./bowman/index.js').then((m) => m.Bowman),
  },
  {
    id: 'bloons-td',
    title: 'Bloons TD',
    title_i18n: 'registry.bloons-td.title',
    tagline: 'Waypoints + torres defensivas',
    tagline_i18n: 'registry.bloons-td.tagline',
    level: 4,
    load: () => import('./bloons-td/index.js').then((m) => m.BloonsTD),
  },
  {
    id: 'territory-war',
    title: 'Territory War',
    title_i18n: 'registry.territory-war.title',
    tagline: 'IA de bots, turnos y captura de territorio',
    tagline_i18n: 'registry.territory-war.tagline',
    level: 4,
    load: () => import('./territory-war/index.js').then((m) => m.TerritoryWar),
  },
  {
    id: 'swords-and-souls',
    title: 'Swords and Souls',
    title_i18n: 'registry.swords-and-souls.title',
    tagline: 'Entrenamiento, combate por turnos y subida de nivel',
    tagline_i18n: 'registry.swords-and-souls.tagline',
    level: 5,
    load: () => import('./swords-and-souls/index.js').then((m) => m.SwordsAndSouls),
  },
  {
    id: 'henry-stickmin',
    title: 'Henry Stickmin',
    title_i18n: 'registry.henry-stickmin.title',
    tagline: 'Árbol de decisiones, finales múltiples y humor',
    tagline_i18n: 'registry.henry-stickmin.tagline',
    level: 5,
    load: () => import('./henry-stickmin/index.js').then((m) => m.HenryStickmin),
  },
  // Próximos juegos se añaden aquí siguiendo el mismo patrón.
];
